export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_chaneged'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const EMAIL_EMPTY = 'email_empty'
export const PASSWORD_EMPTY = 'password_empty'
export const FIELDS_EMPTY = 'fields_empty'